export const NAVIGATE = "NAVIGATE";
export const NEW_ALERT = "NEW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const PERSIST_SETTINGS = "PERSIST_SETTINGS";
export const LOAD_SETTINGS = "LOAD_SETTINGS";
export const LOADED_SETTINGS = "LOADED_SETTINGS";
export const EDIT_SETTING = "EDIT_SETTING";
export const OVEN_CONNECTED = "OVEN_CONNECTED";
export const OVEN_DISCONNECTED = "OVEN_DISCONNECTED";
export const SOCKET_ERROR = "SOCKET_ERROR";

export const START_REFLOW = "START_REFLOW";
export const STARTED_REFLOW = "STARTED_REFLOW";

export const CANCEL_REFLOW = "CANCEL_REFLOW";
export const CANCELED_REFLOW = "CANCELED_REFLOW";

export const GET_STATUS = "GET_STATUS";
export const STATUS = "STATUS";
